# 🏢 ENTERPRISE MODE CONFIGURATION
# Professional pentesting and enterprise assessment

output: "pretty"
verbose: "info"
quiet: false

# Balanced performance settings
max-connection-per-host: 15
max-parallel-hosts: 150
timeout: "20s"
delay: "100ms"

# Enterprise performance
adaptive-concurrency: true
target-response-time: "500ms"
performance-mode: "balanced"
max-memory: 3000
enable-cache: true
max-cache-size: 1000

# Moderate stealth
enable-stealth: true
stealth-mode: "ninja"
stealth-delay-min: 200
stealth-delay-max: 800

# Professional AI features
enable-all-ai-features: false
enable-parameter-discovery: true
enable-vulnerability-detection: true
enable-response-intelligence: true
enable-smart-wordlist-generation: true

# Professional discovery
enable-multi-method-discovery: true
enable-header-based-discovery: true
enable-encoding-bypass: true

# Comprehensive reporting
enable-risk-scoring: true
risk-threshold: "medium"
enable-advanced-output: true
output-formats: [ "json", "csv", "html", "sarif", "burp" ]

# Enterprise notifications
enable-notifications: true
notification-level: "high"

# Professional settings
researcher: "Security Team"
bounty-platform: "internal"
bounty-program: "Enterprise Assessment"

# Comprehensive reports
output-dir: "./enterprise-assessment"
html-report: "./enterprise-assessment/security-report.html"
markdown-report: "./enterprise-assessment/executive-summary.md"
burp-output: "./enterprise-assessment/burp-project.burp"
sarif-output: "./enterprise-assessment/sarif-results.sarif"
nuclei-output: "./enterprise-assessment/nuclei-templates.yaml"

# Professional headers
headers:
  - "x-forwarded-for: 127.0.0.1"
  - "x-real-ip: 127.0.0.1"
  - "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) Enterprise Security Scanner"

# Comprehensive status codes
success-status-codes: [ 200, 201, 202, 204, 301, 302, 307, 308, 401, 403, 422, 500 ]
fail-status-codes: [ 400, 404, 502, 503, 504 ]

# Professional scanning
preflight-depth: 2
quarantine-threshold: 12
wildcard-detection: true

# Enterprise wordlists
assetnote-wordlists:
  - "apiroutes-240528:25000"
  - "parameters-240528:5000"
  - "raft-large-words:10000"
  - "directories-240528:5000"

# Comprehensive coverage
max-redirects: 5

# Professional filtering
ignore-length: [ ]

# Enterprise features
disable-precheck: false
kitebuilder-full-scan: true
progress: true